apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
commonLabels:
  modoki.tsuzu.xyz/id: ""
  modoki.tsuzu.xyz/owner: ""
  modoki.tsuzu.xyz/domain: ""
namespace: "modoki"
nameSuffix: "-1"
