version: 2
jobs:
  build:
    environment:
      - GO111MODULE: "on"
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/modoki-paas/modoki-k8s
    steps:
      - setup_remote_docker
      - checkout
      - run: echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
      - run: make ci
