apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: modoki
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: example@example.com
    privateKeySecretRef:
      name: letsencrypt-staging
    dns01:
      providers:
        - name: cf-dns
          cloudflare:
            email: example@example.com
            apiKeySecretRef:
              name: cloudflare-api-key
              key: api-key.txt
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: apps-tsuzu-xyz
  namespace: modoki
spec:
  secretName: apps-tsuzu-xyz-tls
  issuerRef:
    name: letsencrypt-staging
  commonName: '*.apps.tsuzu.xyz'
  dnsNames:
  - apps.tsuzu.xyz
  acme:
    config:
    - dns01:
        provider: cf-dns
      domains:
      - '*.apps.tsuzu.xyz'
      - apps.tsuzu.xyz
